### ISSUE TITLE
UI hangs for long times on larger texts

### ISSUE THREAD

**Issue by RBogie** [IvanMathy/Boop#143]
When working with bigger files, the editor hangs for large amount of times each time the tokens generated by the lexer are invalidated (so on each paste, text insertion/removal, ...).

As an example I used this reasonably sized json file: http://www.json-generator.com/api/json/get/cfAolJlfma?indent=2 (~85kb)

On my macbook with 6-Core i7 on 2.6ghz this file hangs the UI for around 30 seconds when pasting it into boop. This is caused by the json label regex lexing. When I disable line 70 in `BoopLexer.swift` the time to paste this file is around 1 second. When I disable all lexers that use the `quoteLookahead` regex pattern, it's almost instant.

Since I don't know a lot about swift, savannakit and it's lexers, I'm opening an issue. Maybe with some pointers to how we could solve this, I might be able to work this into a PR fixing it :)

**Comment by IvanMathy** [comment]
Hey there!

Thanks for opening an issue, this has been on my radar since before I released Boop. I've been doing a lot of research on how to approach this and I have been working on performance enhancements for the past couple weeks as part of the [Savannakit repo](https://github.com/IvanMathy/savannakit), which is the editor view within Boop.

First of all; good catch on the JSON regex. Removing it bring in a 70% or so highlighting time reduction. It's a pretty nice improvement but we're still a long way from the high-performance I'd expect from a native editor. Plus, I think the JSON labels being a different colors is my favorite feature of Boop.

I kept digging past this single regex and found out significant issues with the way I do things, and rewrote big parts of the system. Here are the benchmarks results as of right now, highlighting the JSON you linked with the old and WIP version:

<img width="283" alt="Screen Shot 2020-08-03 at 21 20 07" src="https://user-images.githubusercontent.com/646858/89246359-95b80380-d5d0-11ea-9a44-9b72a7819d43.png"> <img width="265" alt="Screen Shot 2020-08-03 at 21 22 50" src="https://user-images.githubusercontent.com/646858/89246367-98b2f400-d5d0-11ea-98cd-7e08b521d95e.png">

As you can see, we're going from about 34s to about 0.1s, or about a 99% time reduction. Once again it's better, though I'm not sure 1/10th of a second is even fast enough to type comfortably.

The reason this is not out yet is because I'm not satisfied with the results yet, and I need even deeper changes to how the system works in order to bring this number down even more. More specifically, I need to improve how single line changes are handled to avoid re-parsing the entire text when typing. I haven't had the time to dive into it lately but hopefully this week I'll have time to sit down and actually get it done. If not, I'll probably do a release of the current state and another update later with additional performance improvements.

I hope this helps shine a bit of light on the situation! I'm aware of it and working towards making it better. There is progress, just not quite enough for my taste yet but it'll get there hopefully soon.

**Comment by RBogie** [comment]
Oh wow, that's very nice to hear! If you need any help brainstorming about how to improve the responsiveness feel free to message me ;) I might not have a lot of experience in swift, but I do know my fair share of native code and performance optimizations.

(And we all know sometimes a rubber duck is enough for getting things done)

**Comment by EladWeinson** [comment]
This also happens for me in version 1.2.1 with plain text that contains a JSON with a size of 136kb.
Maybe is the syntax highlighting will be done asynchronously, I'll be able to see the text and run scripts without waiting (if you think the syntax highlighting is the problem

**Comment by abhi21git** [comment]
@IvanMathy can we please have a beta build with reduced time, I use Boop at least 50times a day and really need beta or something

**Comment by IvanMathy** [comment]
1.3.0 is now under review by Apple, should be released in the next couple days! Closing this issue, feel free to reopen if needed.

**Comment by abhi21git** [comment]
@IvanMathy 1.3.0 is not available here, please update it
https://github.com/IvanMathy/Boop/releases

**Comment by IvanMathy** [comment]
@abhi21git As I said, it will be available in the next couple of days.

**Comment by eexit** [comment]
Hello,

Sorry to dig up this issue but the latest versions of Boop are still very slow. I'm trying to open a JSON file of 200 KB and still nothing after 5 min (2,3 GHz Dual-Core Intel Core i5 / 8 GB 2133 MHz LPDDR3).

Can we make the highlight process a command because it mostly does not make a lot of sense to auto-highlight raw content that has not been necessarily formatted before?

Thanks!
