### ISSUE TITLE
Fetch inside script

### ISSUE THREAD

**Issue by abasse** [IvanMathy/Boop#158]
Hi,

is it possible to run a fetch eg.

fetch('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => response.json())
  .then(json => console.log(json))

inside a script?

I receive:  _ReferenceError: Can't find variable: fetch_

Thanks,

André

**Comment by IvanMathy** [comment]
Hey there! Currently there is no way to access external resources. This is both for security reasons and because of the additional work needed to make those libraries work. I'll definitely keep it in mind. Thanks for the suggestion!

**Comment by nhnicwaller** [comment]
This feels like an anti-feature.

I find Boop much more trusthworthy because it **doesn't** allow network access from within scripts. That reassures me that the built-in scripts aren't sending my secrets anywhere, and it makes me much more confident to install third-party/user-contributed scripts knowing that they also don't have the ability to exfiltrate my data.

On the [boop homepage](https://boop.okat.best) this is the tagline in big, bright, bold characters:

> STOP PASTING COMPANY SECRETS INTO RANDOM WEBSITES.

**Comment by abasse** [comment]
@nhnicwaller I'm very careful with any type of application that I use. This has nothing to do with scriptable or native apps. In 2020 most application use internet technology and http is a big part of. So providing a way for developers to use it in a controlled way would be a plus from my point of view. If required, restrictions eg. only access to localhost or configured networks could be an option to improve security. On top of that such access could also be made only available for custom, local scripts.

**Comment by abasse** [comment]
Switched to another app.

**Comment by IvanMathy** [comment]
Sorry to hear Boop didn't fit your needs, I'd love to still have a conversation and see how we can add your use case while keeping security concerns in check...

Out of curiosity, which app did you switch to? (if you don't mind me asking)
