### ISSUE TITLE
Light mode

### ISSUE THREAD

**Issue by danielbuechele** [IvanMathy/Boop#16]
The app doesn't look good in light mode. The UI is somewhat brown (I assume it mixes the color with my wallpaper), the content of the text field, is hardly readable.

<img width="599" alt="image" src="https://user-images.githubusercontent.com/685740/84796957-29b61780-aff1-11ea-8730-1bfb76796023.png">

**Comment by chockenberry** [comment]
`// Disable light mode because why in heck would you want that???`

Because I'm 60 years old and my eyesight isn't as good as it was 40 years ago?

**Comment by chockenberry** [comment]
This, of course, will have ramifications in DefaultTheme.swift. Everything there and in Colors.swift should be using named colors (which can have light and dark variants).

**Comment by IvanMathy** [comment]
Very fair request, I apologize about the comment I didn't realize this would be an accessibility issue...

I'll add support for the next release and let you know once it's in!

**Comment by pcr910303** [comment]
> I assume it mixes the color with my wallpaper

That's probably macOS dark mode's [Desktop Tinting](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/). Have not read the code yet, but considering that it's automatically supporting these features, it looks like it's probably setting the appearance as `darkAqua` instead of going full hardcoded colors. Looks like making the hardcoded colors an appearance-aware `NSColor` and remove the `darkAqua` setting bit will resolve this.

**Comment by IvanMathy** [comment]
Fixed in #61, please see PR for screenshots!
