### ISSUE TITLE
suggest move boop script to a standalone git repo

### ISSUE THREAD

**Issue by cnzx219** [IvanMathy/Boop#161]
the title as u see

**Comment by IvanMathy** [comment]
Hey there!

As discussed in this comment: https://github.com/IvanMathy/Boop/issues/117#issuecomment-657261607 the reason everything is in the same repo is because I have limited time to maintain Boop (as you can tell by the delay for my reply) and keeping it all in one place is significantly easier for me. I'm open to suggestions to make it better, but so far the influx of new scripts has been slow enough to not make it worth it for me to make the switch.

Feel free to reopen the issue if you'd like to discuss it more!
