### ISSUE TITLE
JWT Decode not working after upgrading to v1.3.0

### ISSUE THREAD

**Issue by athenacykes** [IvanMathy/Boop#184]
I was able to decode JWT with Boop previously, but I now cannot after upgraded to v1.3.0.

Sample JWT for reference:

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImVkYzFiMGQ5NDkwYzQ1ZTFhNGZmNDJlN2Y5Nzg0ZTMyS3JhOElRZVBUcnIifQ.eyJhdWQiOlsiYXBwX2FwaV9yZXNvdXJjZSIsImVudGVycHJpc2VfbW9iaWxlX3Jlc291cmNlIiwiYmZmX2FwaV9yZXNvdXJjZSJdLCJncmFudF90eXBlIjoicGFzc3dvcmQiLCJ1c2VyX25hbWUiOiJSMjAyMDA5MjQzOTQxMTQiLCJzY29wZSI6WyJyZWFkIl0sImV4cCI6MTYwMDk3MDAyNywianRpIjoiMWU0MWMwYjEtY2ZhNi00ZmFkLWJlNWUtOTc1OTljNWIyNGY5IiwiY2xpZW50X2lkIjoiZWRjMWIwZDk0OTBjNDVlMWE0ZmY0MmU3Zjk3ODRlMzJLcmE4SVFlUFRyciJ9.zJFUm_0iTM_6z_RwVcrRO3Uf5V97gtKXlrdVyDXeRfo`

**Comment by IvanMathy** [comment]
Well, turns out I'm an idiot.

#181 actually raised the issue and fixed it while I was in the process of releasing 1.3.0. So I cancelled the release, made a new build, and restarted the process. Except, I guess I didn't swap the build or maybe I picked the wrong one, which means I released the wrong, broken version.

Anyway, 1.3.1 is now out on the App Store so you can update it and the problem will be gone.

Thank you so much for catching my mistake, I really appreciate you taking the time to report it!
