### ISSUE TITLE
it seems that someone ripped off your code

### ISSUE THREAD

**Issue by tessus** [IvanMathy/Boop#239]
looks suspiciously familiar: https://devutils.app/

**Comment by chrstfer** [comment]
Not just suspiciously familiar, even the FAQ is basically the same. That being said, I'm pretty sure this is explicitly allowed by the MIT license. Unfortunate and scummy of the other dev who is selling "their" version for 25$, but not illegal. This is one reason to use GPL!

**Comment by tessus** [comment]
This is true, but the MIT license requires the preservation of copyright and license notices.

**Comment by chrstfer** [comment]
True, and agreed. I tweeted at the account associated with the ripoff, will report back if it gets back to me.

**Comment by trungdq88** [comment]
Hi all, author of DevUtils here. I'm happy to answer any questions.

I built DevUtils from the start of the COVID pandemic without any knowledge of Boop. You can see the list of open-source projects used in DevUtils here https://devutils.app/acknowledgments/.

The idea of DevUtils and Boop is not at all unique or new, if you like offline developer utilities, I also suggest taking a look at [CyberChef](https://gchq.github.io/CyberChef/) (also open-source).

That said, what I really like about Boop is the plug-in system. I plan to introduce custom scripts to DevUtils soon, somewhat like Boop, but more focused on the UX/UI instead of sole text input/output.

If I use any of Boop's code in the future (or even reuse the plugin protocol), I'll make sure Boop is credit properly.

Let me know if there are any questions, I'm happy to address. Cheers!

**Comment by trungdq88** [comment]
> There is a delayed source repo for DevUtils here as well, though it doesn't specify how delayed anywhere that i can see. I didn't see a single link to it anywhere on the DevUtils site though.

The link to GitHub is visible all the time under the footer of https://devutils.app, and also in https://devutils.app/contact/

The DevUtils source code is currently delayed by 2 versions. Although that may change in the future, either longer or shorter.

**Comment by chrstfer** [comment]
I dont know how I missed the link in your footer, i guess I was way more tired than i realized when i was looking through the DevUtils site. My apologies @trungdq88. 

Unless @tessus or anyone else has any further objections/questions, i move that we close the issue as resolved.

**Comment by tessus** [comment]
Yes. This is fine with me. When I opened the issue, I didn't even see that the code was on github. I just came scross that web site and I thought: _hey, I know this from somewhere._
